#include "gtest/gtest.h"
#include <iomanip>
#include <iostream>

//------------------------------------------------------------------------------
// Files we are testing:

//------------------------------------------------------------------------------

using namespace std;

//------------------------------------------------------------------------------
//          COPY BASIC_TEST INTO THIS FILE.
//                    AND THEN,
//         DO NOT EDIT THIS FILE ANY FURTHER
//------------------------------------------------------------------------------

bool test_stub(bool debug = false)
{
    return true;
}

// Lord help me!
const bool debug = false;

TEST(TEST_STUB, TestStub)
{
    bool success = test_stub(debug);
    EXPECT_EQ(success, true);
}

int main(int argc, char** argv)
{
    ::testing::InitGoogleTest(&argc, argv);
    std::cout << "\n\n----------running instruction.cpp---------\n\n"
              << std::endl;
    return RUN_ALL_TESTS();
}
