#include "gtest/gtest.h"
#include <iomanip>
#include <iostream>

//------------------------------------------------------------------------------
// Files we are testing:
#include "../../includes/sql/sql.h"
//------------------------------------------------------------------------------

using namespace std;

//------------------------------------------------------------------------------
//          COPY BASIC_TEST INTO THIS FILE.
//                    AND THEN,
//         DO NOT EDIT THIS FILE ANY FURTHER
//------------------------------------------------------------------------------
const vector<string> command_list = {
    "create table studentSample001 fields 	fname, 			lname, 		major, 				age",
    "insert into studentSample001 values 	Flo, 			Yao, 		CS, 				20",
    "insert into studentSample001 values 	\"Flo\", 			\"Jackson\", 	Math,	 			21",
    "insert into studentSample001 values 	Calvin, 		Woo, 		Physics,			22",
    "insert into studentSample001 values 	\"Anna Grace\", 	\"Del Rio\", 	CS,	 				22",
};

const vector<string> select_list =
    {
        "select * from studentSample001 where lname > Yang",

        "select * from studentSample001 where age > 50",

        "select * from studentSample001 where age  > 53",

        "select * from studentSample001 where age > 54",

        "select * from studentSample001 where lname >= Yang",

        "select * from studentSample001 where lname < Jackson",
        "select * from studentSample001 where lname <= Smith",
        "select * from studentSample001 where fname = \"Flo\" and lname = \"Yao\"",
        "select * from studentSample001 where fname = Flo or lname = Jackson",
        "select * from studentSample001 where fname = Flo or major = CS and age <= 23",
        "select * from studentSample001 where age <30 and major=CS or major = Physics and lname = Jackson",
        "select * from studentSample001 where lname = Yang or major = CS and age < 23 or lname = Jackson",

        // "select * from employeeSample01 where last >= Jack",

        // //.................
        // //:Less Than      :
        // //.................
        // //. . . . . . . . . . . . . (Less Than: Non-existing) . . . . . . . . . . . . .
        // select * from studentSample01 where lname < Jackson

        // //. . . . . . . . . . . . . (Less than: first item) . . . . . . . . . . . . . .
        // select * from studentSample01 where age  < 20

        // //. . . . . . . . . . . . . (Less Than: before first item) . . . . . . . . . . .
        // select * from studentSample01 where age  < 19

        // //.................
        // //:Less Equal     :
        // //.................
        // select * from studentSample01 where lname <= Smith

        // //. . . . . .  (Less Equal non-existing: ) . . . . . . . . . . .
        // select * from employeeSample01 where last <= Peach

        // //******************************************************************************
        // //		LOGICAL OPERATORS
        // //******************************************************************************

        // //.................
        // //:AND            :
        // //.................
        // select * from studentSample01 where fname = "Flo" and lname = "Yao"

        // //.................
        // //:OR            :
        // //.................
        // select * from studentSample01 where fname = Flo or lname = Jackson

        // //.................
        // //:OR AND         :
        // //.................
        // select * from studentSample01 where fname = Flo or major = CS and age <= 23

        // //.................
        // //:AND OR AND     :
        // //.................
        // select * from studentSample01 where age <30 and major=CS or major = Physics and lname = Jackson

        // //.................
        // //:OR AND OR      :
        // //.................
        // select * from studentSample01 where lname = Yang or major = CS and age < 23 or lname = Jackson
};

bool sql_batch(bool debug = false)
{
    remove("employeeSample01.bin");
    remove("employeeSample01_fields.bin");
    remove("studentSample01.bin");
    remove("studentSample01_fields.bin");

    SQL sql;
    string s = "_!sample01.txt";
    sql.batch(s.c_str());

    remove("employeeSample01.bin");
    remove("employeeSample01_fields.bin");
    remove("studentSample01.bin");
    remove("studentSample01_fields.bin");

    // remove("studentSelect02.bin");
    // remove("studentSelect02_fields.bin");
    // remove("employeeSample02.bin");
    // remove("employeeSample02_fields.bin");
    // // SQL sql;
    // // string
    // s = "_!sample02.txt";
    // sql.batch(s.c_str());

    // remove("studentSelect02.bin");
    // remove("studentSelect02_fields.bin");
    // remove("employeeSample02.bin");
    // remove("employeeSample02_fields.bin");
    return true;
}

// Lord help me!
const bool debug = false;

TEST(SQL_BASIC, SQLBatch)
{
    bool success = sql_batch(debug);
    EXPECT_EQ(success, true);
}

int main(int argc, char** argv)
{
    ::testing::InitGoogleTest(&argc, argv);
    std::cout << "\n\n----------running instruction.cpp---------\n\n"
              << std::endl;
    return RUN_ALL_TESTS();
}
